# Generated by Django 5.1.2 on 2025-03-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_visibilty_review_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
