# Generated by Django 5.1.2 on 2025-03-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
