# Generated by Django 5.1.2 on 2025-02-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
    ]
