# Generated by Django 5.1.2 on 2025-02-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Guest', 'Guest')], default='User', max_length=7),
        ),
    ]
